### ISSUE TITLE
Tasks are not automatically invoked on Windows

### ISSUE THREAD

**Issue by stereokai** [timolins/hyperlayout#17]
The fix is to change 
```js
function runCommand(uid, cmd) {
  window.rpc.emit('data', {
    uid,
    data: ` ${cmd}\n`
  })
}
```
To this:
```js
function runCommand(uid, cmd) {
  window.rpc.emit('data', {
    uid,
    data: ` ${cmd}\n\r`
  })
}
```
I'm not sure how it would affect Mac/Linux though, and then do we need to check for current OS environment

**Comment by timolins** [comment]
Makes sense! Will give tt a try on my Mac as soon as I can.

**Comment by stereokai** [comment]
Awesome! 🙌

**Comment by colinbate** [comment]
I'm not sure whether this is due to a new version of Hyper (1.3.2), but this is now "broken". First off, it should have been `\r\n` (note the `\r` first). But even that seems to cause issues now. The second "enter" key gets sent to the session. I was running some servers which are setup to quit upon any key stroke in the console, and they were being run and then immediately quit because of an extra "enter" key being sent to them.

**Comment by colinbate** [comment]
Perhaps Hyper is being clever about which line ending to send based on OS.
