### ISSUE TITLE
Can't find layout inside config

### ISSUE THREAD

**Issue by kevingelion** [timolins/hyperlayout#7]
Hey there,
Thanks for your hard work on this project 😄 

I've placed the following in my `~/.hyperlayout` file:
```
{
  "name": "example-2",
  "hyperlayout": {
      "start": [
        [[
          "npm run watch",
          ["npm run serve", "http://localhost:3000"]
        ]]
      ],
      "helloworld": {
        "entry": "horizontal",
        "layout": [
          "echo 'Hello'",
          "echo 'World'"
        ]
      }
  }
}
```

I get the following error: `Can't find layout inside config`. I looked through the source and it's looking for `config.layout`. Your examples don't reflect that particular JSON object is necessary. Is my JSON incorrect for leaving inside `~/.hyperlayout`? I've tried all of your other basic examples and get the same errors on all of them.

**Comment by timolins** [comment]
Thanks for letting me know!

The problem here is, that you defined it like `package.json` and not in the correct `.hyperlayout` style. The same example would look like this: 
```json
{
  "start": [
    [[
      "npm run watch",
      ["npm run serve", "http://localhost:3000"]
    ]]
  ],
  "helloworld": {
    "entry": "horizontal",
    "layout": [
      "echo 'Hello'",
      "echo 'World'"
    ]
  }
}
```

And since the preset `default` isn't defined, running `hyperlayout` will do nothing. You have to select which one you want, for example: 
```
$ hyperlayout helloworld
```

I hope this is a bit more clear now.  There is is still documentation missing on that topic, I will close this issue when I explained it a bit further in the README.
